application: your-app-id
version: 1
runtime: python27
api_version: 1
# Mimic target environment is not yet threadsafe
threadsafe: false

includes:
- mimic.yaml

# https://developers.google.com/appengine/docs/python/config/appconfig#Builtin_Handlers
builtins:
- admin_redirect: on
- appstats: on
- deferred: on
- remote_api: on

# Currently supported inbound services are documented by
# https://developers.google.com/appengine/docs/python/config/appconfig#Inbound_Services
inbound_services:
- channel_presence
- mail
- xmpp_message
- xmpp_presence
- xmpp_subscribe
- warmup

# Currently supported libraries are documented by
# https://developers.google.com/appengine/docs/python/tools/libraries27
# Keep in sync with target_info.py library validation code.
libraries:
- name: django
  version: latest
- name: jinja2
  version: latest
- name: lxml
  version: latest
- name: markupsafe
  version: latest
- name: numpy
  version: latest
- name: PIL
  version: latest
- name: pycrypto
  version: latest
- name: setuptools
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: yaml
  version: latest
